apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: loki
    release: loki
  name: storage-loki-0
  namespace: loki
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: loki-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
