kind: PersistentVolume
apiVersion: v1
metadata:
  name: ceph-pv-grafana
  labels:
    type: local
spec:
  storageClassName: ceph-block
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path:  /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-pvc-grafana
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi